"""Actual React fitting room and garment inventory at 1080p/4K, browser and NUI modes."""
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

Path('.codex-log').mkdir(exist_ok=True)
with sync_playwright() as p:
    browser=p.chromium.launch(channel='chrome',headless=True)
    page=browser.new_page(viewport={'width':1920,'height':1080})
    errors=[]
    page.on('pageerror',lambda e: errors.append(str(e)))
    page.goto('http://127.0.0.1:5173/?view=clothing',wait_until='networkidle')
    expect(page.locator('.clothing-product')).to_have_count(13)
    expect(page.locator('.clothing-product').first).to_have_attribute('aria-label','Aktuell')
    expect(page.get_by_role('button',name='Kaufen',exact=True)).to_be_disabled()
    expect(page.get_by_role('checkbox',name='Direkt anziehen')).not_to_be_checked()
    fixture=page.evaluate("async()=> (await import('/src/lib/clothingPreview.ts')).clothingPreview()")
    for garment in fixture['currentClothing']:
        category=next(o['category'] for o in fixture['offers'] if o['garment']['category']==garment['category'])
        page.get_by_role('navigation',name='Kategorien').get_by_role('button',name=category,exact=True).click()
        expect(page.locator('.clothing-current .catalog-image image')).to_have_attribute('href',f"catalog/{garment['artwork']}.webp")
    page.get_by_role('navigation',name='Kategorien').get_by_role('button',name='Oberteile',exact=True).click()
    page.locator('.clothing-product').nth(2).click()
    expect(page.locator('.clothing-current .catalog-image image')).to_have_attribute('href','catalog/clothing/0/top/0_0.webp')
    page.get_by_role('button',name='Hosen',exact=True).click()
    expect(page.locator('.clothing-product')).to_have_count(13)
    expect(page.get_by_role('button',name='Unterkörper',exact=True)).to_have_attribute('aria-pressed','true')
    page.get_by_role('textbox',name='Kleidung suchen').fill('Schiefergraue')
    expect(page.locator('.clothing-product')).to_have_count(2)
    expect(page.locator('.clothing-product').first).to_have_attribute('aria-label','Aktuell')
    page.locator('.clothing-product').nth(1).click()
    expect(page.locator('.clothing-selected')).to_contain_text('2 Teile')
    page.get_by_role('button',name='Oberteile',exact=True).click()
    expect(page.locator('.clothing-product').nth(2)).to_have_attribute('aria-pressed','true')
    page.get_by_role('button',name='Aktuell',exact=True).click()
    expect(page.locator('.clothing-selected')).to_contain_text('1 Teil')
    page.locator('.clothing-product').nth(2).click()
    page.get_by_role('button',name='Hosen',exact=True).click()
    expect(page.locator('.clothing-product').nth(2)).to_have_attribute('aria-pressed','true')
    page.get_by_role('button',name='Kaufen',exact=True).click()
    expect(page.locator('.clothing-notice')).to_contain_text('Schiefergraue Jeans gekauft')
    expect(page.get_by_role('button',name='Bargeld')).to_contain_text('$2.747')
    expect(page.locator('.clothing-current')).to_contain_text('Schiefergraue Jeans')
    expect(page.locator('.clothing-selected')).to_contain_text('1 Teil')
    page.get_by_role('navigation',name='Kategorien').get_by_role('button',name='Schuhe',exact=True).click()
    chosen_shoes=page.locator('.clothing-product').nth(2).locator('.catalog-image image').get_attribute('href')
    page.locator('.clothing-product').nth(2).click()
    page.get_by_role('checkbox',name='Direkt anziehen').check()
    page.get_by_role('button',name='Alles kaufen',exact=True).click()
    expect(page.locator('.clothing-notice')).to_contain_text('2 Kleidungsstücke gekauft. Direkt angezogen.')
    expect(page.get_by_role('button',name='Bargeld')).to_contain_text('$2.455')
    expect(page.locator('.clothing-current')).to_contain_text('Schwarze Oxfords')
    expect(page.locator('.clothing-current .catalog-image image')).to_have_attribute('href',chosen_shoes)
    expect(page.get_by_role('button',name='Alles kaufen',exact=True)).to_be_disabled()
    page.get_by_role('button',name='Oberteile',exact=True).click()
    expect(page.locator('.clothing-current')).to_contain_text('Weißes Shirt mit V-Ausschnitt')
    expect(page.locator('.clothing-current .catalog-image image')).to_have_attribute('href','catalog/clothing/0/top/1_0.webp')
    page.get_by_role('button',name='Nur Anprobe',exact=True).click()
    expect(page.locator('.clothing-panel')).to_be_hidden()
    area=page.locator('.camera-drag-area').bounding_box()
    page.mouse.move(area['x']+100,area['y']+100);page.mouse.down()
    page.mouse.move(area['x']+300,area['y']+180,steps=8);page.mouse.up()
    expect(page.locator('.camera-readout')).to_contain_text('56°')
    page.get_by_role('button',name='Sortiment anzeigen',exact=True).click()
    page.get_by_role('button',name='Brillen',exact=True).click()
    expect(page.get_by_role('button',name='Gesicht',exact=True)).to_have_attribute('aria-pressed','true')
    for width,height in [(1920,1080),(3840,2160),(1280,720)]:
        page.set_viewport_size({'width':width,'height':height})
        panel=page.locator('.clothing-panel').bounding_box()
        categories=page.locator('.clothing-categories').bounding_box()
        buy=page.get_by_role('button',name='Kaufen',exact=True).bounding_box()
        assert panel['x']+panel['width']<=width and panel['y']+panel['height']<=height
        assert categories['x']+categories['width']<panel['x']
        assert buy['y']+buy['height']<height
        assert panel['width']/width < .34
        page.screenshot(path=f'.codex-log/clothing-{width}.png')
    page.set_viewport_size({'width':1920,'height':1080})
    page.goto('http://127.0.0.1:5173/?view=inventory',wait_until='networkidle')
    slot=lambda side,n: page.locator(f'.inventory-slot[data-side="{side}"][data-slot="{n}"]')
    expect(slot('own',17)).to_contain_text('Angezogen')
    slot('own',17).click(button='right')
    page.get_by_role('button',name='Ausziehen',exact=True).click()
    expect(slot('own',17).locator('.inventory-worn')).to_have_count(0)
    slot('own',17).click(button='right')
    page.get_by_role('button',name='Anziehen',exact=True).click()
    expect(slot('own',17)).to_contain_text('Angezogen')
    def drag(a,b):
        aa,bb=a.bounding_box(),b.bounding_box()
        page.mouse.move(aa['x']+30,aa['y']+40);page.mouse.down()
        page.mouse.move(bb['x']+30,bb['y']+40,steps=10);page.mouse.up()
    drag(slot('own',17),slot('own',20))
    expect(slot('own',20)).to_contain_text('Angezogen')
    drag(slot('own',20),slot('external',4))
    expect(slot('external',4)).to_contain_text('Crew-T-Shirt')
    expect(slot('external',4).locator('.inventory-worn')).to_have_count(0)
    drag(slot('external',4),slot('own',20))
    expect(slot('own',20).locator('.inventory-worn')).to_have_count(0)
    page.screenshot(path='.codex-log/clothing-inventory.png')
    # Runtime mode: all preview/camera requests go through their own typed NUI route.
    page.add_init_script("window.GetParentResourceName=()=> 'rp_ui'")
    requests=[]
    def nui(route):
        requests.append((route.request.url,route.request.post_data_json))
        route.fulfill(status=200,content_type='application/json',body='{"ok":true}')
    page.route('https://rp_ui/**',nui)
    page.goto('http://127.0.0.1:5173/?view=clothing',wait_until='networkidle')
    fixture=page.evaluate("async()=> (await import('/src/lib/clothingPreview.ts')).clothingPreview()")
    page.evaluate("payload=>window.postMessage({action:'ui:open',data:{view:'clothing',locked:false,payload}},'*')",fixture)
    expect(page.get_by_role('button',name='Kaufen',exact=True)).to_be_disabled()
    page.locator('.clothing-product').nth(2).click()
    page.get_by_role('navigation',name='Kategorien').get_by_role('button',name='Schuhe',exact=True).click()
    page.locator('.clothing-product').nth(1).click()
    page.wait_for_timeout(150)
    assert any(url.endswith('rp_clothing:preview') and set(data['products'])=={'top_0_1','shoes_0_1'} for url,data in requests)
    assert any(url.endswith('rp_clothing:camera') and data['view']=='shoes' for url,data in requests)
    assert not any(url.endswith('rp_characters:camera') for url,_ in requests)
    page.get_by_role('button',name='Kaufen',exact=True).click()
    expect(page.locator('.clothing-notice')).to_contain_text('gekauft')
    singles=[data for url,data in requests if url.endswith('rp_clothing:buy')]
    assert singles[-1]['action']=='buyOutfit' and singles[-1]['products']==['shoes_0_1'] and singles[-1]['equip'] is False
    page.get_by_role('checkbox',name='Direkt anziehen').check()
    page.get_by_role('button',name='Alles kaufen',exact=True).click()
    expect(page.locator('.clothing-selected')).to_contain_text('Stelle dein Outfit')
    batches=[data for url,data in requests if url.endswith('rp_clothing:buy')]
    assert batches[-1]['products']==['top_0_1'] and batches[-1]['equip'] is True
    page.keyboard.press('Escape');expect(page.locator('.clothing-screen')).to_have_count(0)
    # A female current outfit/color comes from NUI, independently of shop choices.
    fixture['currentClothing']=[dict(category='top',label='Aktuelles Oberteil',image='top',color='#b5b9b4',artwork='clothing/1/top/0_1')]
    page.evaluate("payload=>window.postMessage({action:'ui:open',data:{view:'clothing',locked:false,payload}},'*')",fixture)
    expect(page.locator('.clothing-current .catalog-image image')).to_have_attribute('href','catalog/clothing/1/top/0_1.webp')
    page.locator('.clothing-product').nth(2).click()
    expect(page.locator('.clothing-current .catalog-image image')).to_have_attribute('href','catalog/clothing/1/top/0_1.webp')
    page.keyboard.press('Escape');expect(page.locator('.clothing-screen')).to_have_count(0)
    assert not errors,errors
    browser.close()
print('PASS: clothing categories/search/purchase/camera, 720p/1080p/4K, worn items and cross-store drag, runtime NUI routes')
