"""Calls, contacts and chat: spatial keys, preview data, responsive layout and forms."""
from pathlib import Path
from playwright.sync_api import sync_playwright, expect
from phone_keyboard import PhoneKeyboard

Path('.codex-log').mkdir(exist_ok=True)
with sync_playwright() as p:
    browser = p.chromium.launch(channel='chrome', headless=True)
    page = browser.new_page(viewport={'width':1920,'height':1080})
    errors = []
    page.on('pageerror', lambda e: errors.append(str(e)))
    page.goto('http://127.0.0.1:5173/?view=phone', wait_until='networkidle')
    phone = PhoneKeyboard(page)
    phone.app('Anrufe')
    for digit in '5550000002':
        phone.choose(digit)
    expect(page.locator('.comm-dial-number strong')).to_have_text('5550000002')
    phone.choose('Letzte Ziffer löschen')
    expect(page.locator('.comm-dial-number strong')).to_have_text('555000000')
    phone.choose('2')
    # All dial-pad controls and app tabs fit, also on small and 4K viewports.
    for width, height in [(1280,720),(1920,1080),(3840,2160),(3440,1440),(740,900)]:
        page.set_viewport_size({'width':width,'height':height})
        page.wait_for_timeout(150)
        bounds = page.locator('.phone-app-content').bounding_box()
        for control in page.locator('[data-phone-action]').all():
            box = control.bounding_box()
            assert box['x'] >= bounds['x']-1 and box['x']+box['width'] <= bounds['x']+bounds['width']+1
            assert box['y'] >= bounds['y']-1 and box['y']+box['height'] <= bounds['y']+bounds['height']+1, (width,control.get_attribute('aria-label'),box,bounds)
        if width == 3840:
            page.screenshot(path='.codex-log/phone-keypad-4k.png')
    page.set_viewport_size({'width':1920,'height':1080})
    page.locator('.phone-device').screenshot(path='.codex-log/phone-keypad.png')
    phone.choose('Anrufen')
    expect(page.locator('.phone-call-title')).to_contain_text('Lena Fischer')
    phone.choose('Mikrofon stummschalten')
    expect(page.locator('.phone-call-members')).to_contain_text('Mikro aus')
    phone.choose('Teilnehmer hinzufügen')
    phone.fill({'Telefonnummer':'5550000003'})
    expect(page.locator('.phone-call-title')).to_contain_text('Konferenz')
    page.locator('.phone-device').screenshot(path='.codex-log/phone-conference.png')
    phone.choose('Auflegen')
    phone.choose('Anrufliste')
    expect(page.locator('.comm-history-row')).to_have_count(6)
    phone.choose('Verpasst')
    expect(page.locator('.comm-history-row')).to_have_count(1)
    expect(page.locator('.comm-history-row')).to_contain_text('Lena Fischer')
    phone.choose('Alle')
    page.locator('.phone-device').screenshot(path='.codex-log/phone-history.png')
    phone.choose('Kontakte')
    expect(page.locator('.comm-letter')).to_have_text(['L','M','S','T'])
    phone.choose('Kontakt suchen')
    phone.fill({'Name oder Nummer':'Sofia'})
    expect(page.locator('.comm-list-item')).to_have_count(1)
    phone.choose('Sofia Costa')
    phone.choose('Anrufen')
    expect(page.locator('.phone-call-title')).to_contain_text('Sofia Costa')
    phone.choose('Auflegen')
    phone.app('Contacts')
    page.locator('.phone-device').screenshot(path='.codex-log/phone-contacts.png')
    phone.choose('Kontakt hinzufügen')
    phone.fill({'Name':'Alice Test','Nummer':'5550000006'})
    expect(page.locator('.comm-person')).to_contain_text('Alice Test')
    phone.choose('Kontakt bearbeiten')
    phone.fill({'Name':'Alice Cooper','Nummer':'5550000006'})
    expect(page.locator('.comm-person')).to_contain_text('Alice Cooper')
    phone.choose('Nachricht schreiben')
    expect(page.locator('.phone-communication')).to_have_attribute('data-screen','thread')
    phone.choose('Nachricht schreiben')
    phone.fill({'Nachricht':'Hallo Alice! Grüße aus Los Santos.'})
    expect(page.locator('.comm-bubble.mine')).to_contain_text('Hallo Alice!')
    phone.choose('Kontaktinfo Alice Cooper')
    phone.press('Backspace')
    expect(page.locator('.phone-communication')).to_have_attribute('data-screen','thread')
    phone.press('Backspace')
    expect(page.locator('.phone-communication')).to_have_attribute('data-screen','root')
    expect(page.locator('.comm-thread-row').first).to_contain_text('Alice Cooper')
    phone.choose('Lena Fischer')
    expect(page.locator('.comm-bubble')).to_have_count(3)
    page.locator('.phone-device').screenshot(path='.codex-log/phone-chat.png')
    phone.press('Backspace')
    expect(page.locator('[data-phone-action="thread:5550000002"] .comm-unread')).not_to_have_class('comm-unread on')
    page.locator('.phone-device').screenshot(path='.codex-log/phone-messages.png')
    # New-message form rejects invalid numbers and preserves the draft.
    phone.choose('Neue Nachricht')
    page.get_by_label('An',exact=True).fill('123')
    page.get_by_label('Nachricht',exact=True).fill('Bleibt als Entwurf.')
    phone.press('Enter')
    expect(page.locator('.phone-app-error')).to_contain_text('Empfänger')
    expect(page.get_by_label('Nachricht',exact=True)).to_have_value('Bleibt als Entwurf.')
    phone.press('Escape')
    phone.app('Contacts');phone.choose('Alice Cooper');phone.choose('Kontakt löschen')
    phone.press('ArrowDown');phone.press('Enter');page.wait_for_timeout(700)
    expect(page.locator('.comm-list-item')).to_have_count(4)
    # Physical Home / Recents stay reachable below the app's last row.
    phone.app('Anrufe');phone.select('Ziffernblock');phone.press('ArrowDown')
    expect(page.locator('.phone-navigation [aria-label="Home"]')).to_have_attribute('aria-pressed','true')
    phone.press('Enter');expect(page.locator('.phone-device')).to_have_attribute('data-page','home')
    page.keyboard.press('Control+a');assert page.evaluate('getSelection().toString()') == ''
    assert not errors, errors
    browser.close()
print('phone-communication-ui: dial pad, history, contact CRUD/direct calls, chat/read status, drafts, conference, keyboard navigation and 5 resolutions passed')
