"""iFruit: real keyboard navigation, identities, feeds, photos, comments and forms."""
from pathlib import Path
from playwright.sync_api import sync_playwright, expect
from phone_keyboard import PhoneKeyboard
from phone_local_keyboard import LocalPhoneKeyboard

Path('.codex-log').mkdir(exist_ok=True)
with sync_playwright() as p:
    browser=p.chromium.launch(channel='chrome',headless=True)
    context=browser.new_context(viewport={'width':1920,'height':1080})
    page=context.new_page(); errors=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.goto('http://127.0.0.1:5173/?view=phone',wait_until='networkidle')
    keys=PhoneKeyboard(page);keys.app('iFruit')
    expect(page.locator('.social-post')).to_have_count(6)
    keys.choose('Gefällt mir @lena.fischer')
    expect(page.locator('.social-post-copy').first).to_contain_text('25 Gefällt mir')
    keys.choose('Like entfernen @lena.fischer')
    expect(page.locator('.social-post-copy').first).to_contain_text('24 Gefällt mir')
    keys.choose('Kommentare @lena.fischer');expect(page.locator('.social-comment')).to_have_count(2)
    keys.choose('Kommentar schreiben');keys.fill({'Dein Kommentar':'Bis gleich am Strand!'})
    expect(page.locator('.social-comment').first).to_contain_text('test_joost')
    expect(page.locator('.social-comment').first).to_contain_text('Bis gleich am Strand!')
    page.locator('.phone-device').screenshot(path='.codex-log/ifruit-comments.png')
    keys.press('Backspace');keys.choose('Freunde')
    expect(page.locator('.social-post')).to_have_count(1)
    expect(page.locator('.social-post')).to_contain_text('lena.fischer')
    keys.choose('Profil @lena.fischer');keys.choose('Nicht mehr folgen')
    keys.choose('Freunde');expect(page.locator('.social-post')).to_have_count(0)
    keys.choose('Profile suchen');keys.choose('Benutzername suchen');keys.fill({'Benutzername':'marc'})
    expect(page.locator('.social-person')).to_have_count(1)
    keys.choose('Folgen @marc.weber');keys.choose('Freunde')
    expect(page.locator('.social-post')).to_have_count(1)
    expect(page.locator('.social-post')).to_contain_text('marc.weber')
    keys.choose('Mein Profil');expect(page.locator('.social-bio')).to_contain_text('Angemeldet als @test_joost')
    keys.choose('Profil bearbeiten');keys.fill({'Benutzername':'test_joost','Anzeigename':'Test Joost','Bio':'Neue Perspektiven. Los Santos.'})
    expect(page.locator('.social-bio')).to_contain_text('Neue Perspektiven.')
    for width,height in [(1280,720),(1920,1080),(3840,2160),(3440,1440),(740,900)]:
        page.set_viewport_size({'width':width,'height':height});page.wait_for_timeout(180)
        area=page.locator('.phone-app-content').bounding_box()
        for item in page.locator('.social-heading,.social-tabs,.social-profile-top').all():
            b=item.bounding_box()
            assert b['x']>=area['x']-1 and b['x']+b['width']<=area['x']+area['width']+1,(width,b,area)
            assert b['y']>=area['y']-1 and b['y']+b['height']<=area['y']+area['height']+1,(width,b,area)
        if width==3840: page.locator('.phone-device').screenshot(path='.codex-log/ifruit-profile-4k.png')
    page.set_viewport_size({'width':1920,'height':1080})
    keys.choose('Profil wechseln');expect(page.locator('.social-person')).to_have_count(2)
    expect(page.get_by_role('button',name='Weiteres Profil erstellen',exact=True)).to_have_count(0)
    keys.choose('Wechseln zu @joost.motors')
    expect(page.locator('.social-bio')).to_contain_text('Angemeldet als @joost.motors')
    keys.choose('Freunde');expect(page.locator('.social-post')).to_have_count(0)
    # Returning to the app preserves the active identity, but not telephone state.
    keys.home();keys.app('iFruit');keys.choose('Mein Profil')
    expect(page.locator('.social-bio')).to_contain_text('@joost.motors')
    # Take a real local browser photo, select it directly in the social composer.
    local=LocalPhoneKeyboard(page);local.app('Camera');local.choose('Foto aufnehmen');page.wait_for_timeout(900)
    keys.app('iFruit');keys.choose('Neuer Fotobeitrag')
    expect(page.locator('.social-grid .social-photo img')).to_have_count(1)
    keys.choose(page.locator('[data-phone-action^="local:"]').get_attribute('aria-label'))
    expect(page.locator('.phone-form')).to_contain_text('@joost.motors')
    keys.fill({'Bildunterschrift':'Unser neuer Showroom.'})
    expect(page.locator('.social-bio')).to_contain_text('@joost.motors')
    expect(page.locator('.social-grid .social-photo')).to_have_count(2)
    keys.choose(page.locator('[data-phone-action^="tile:"]').first.get_attribute('aria-label'))
    expect(page.locator('.social-post')).to_contain_text('Unser neuer Showroom.')
    expect(page.locator('.social-post')).to_contain_text('joost.motors')
    keys.choose('Beitrag löschen');keys.press('ArrowDown');keys.press('Enter');page.wait_for_timeout(900)
    expect(page.locator('.social-grid .social-photo')).to_have_count(1)
    keys.choose('Profil wechseln');keys.choose('Wechseln zu @test_joost')
    keys.choose('Freunde');expect(page.locator('.social-post')).to_contain_text('marc.weber')
    page.keyboard.press('Control+a');assert page.evaluate('getSelection().toString()')==''
    # Empty/new character registers just one identity and handles validation errors.
    fresh=context.new_page();fresh.on('pageerror',lambda e:errors.append(str(e)))
    fresh.goto('http://127.0.0.1:5173/?view=phone&phoneDemo=0',wait_until='networkidle')
    new=PhoneKeyboard(fresh);new.app('iFruit');new.choose('Profil erstellen')
    fresh.get_by_label('Benutzername',exact=True).fill('!bad')
    fresh.get_by_label('Anzeigename',exact=True).fill('Alice')
    new.press('Enter');expect(fresh.locator('.phone-app-error')).to_contain_text('Eingaben')
    expect(fresh.get_by_label('Anzeigename',exact=True)).to_have_value('Alice')
    new.press('Escape');expect(fresh.locator('.phone-form')).to_have_count(0)
    new.choose('Profil erstellen');new.fill({'Benutzername':'alice','Anzeigename':'Alice','Bio':'Hallo Los Santos.'})
    new.choose('Profil wechseln');expect(fresh.locator('.social-person')).to_have_count(1)
    expect(fresh.get_by_role('button',name='Weiteres Profil erstellen',exact=True)).to_have_count(0)
    new.home();new.press('Backspace');expect(fresh.locator('.phone-device')).to_have_attribute('data-open','false')
    assert not errors,errors
    browser.close()
print('phone-social-ui: feeds, likes, comments, following, profiles, switching, local photo publication, deletion, keyboard, error escape and 5 resolutions passed')
