export const screens = [
  { id:'banking', title:'Geldautomat · Fleeca', group:'Spielmenüs', description:'GTA-Geldautomat: Einzahlen, Auszahlen, Empfängerprüfung, Überweisen und Verlauf.', source:'views/Banking.tsx', css:'banking.css', symbol:'ATM' },
  { id:'atm-maze', title:'Geldautomat · Maze', group:'Spielmenüs', description:'Rote Maze-Bank-Variante des Geldautomaten mit funktionierenden Demobuchungen.', source:'views/Banking.tsx', css:'banking.css', symbol:'ATM' },
  { id:'atm-liberty', title:'Geldautomat · Liberty', group:'Spielmenüs', description:'Blaue Automaten-Variante. Alle Banken verwenden das bestehende ESX-Konto.', source:'views/Banking.tsx', css:'banking.css', symbol:'ATM' },
  { id: "loadscreen", title: "Server-Ladebildschirm", group: "Einreise", description: "GTA-Ladesequenz beim Verbinden: Hintergrundmotiv, Hinweise und simulierter FiveM-Fortschritt.", source: "loading/LoadingScreen.tsx", css: "loading/loading.css", symbol: "LS" },
  { id: "clothing", title: "Kleidungsladen", group: "Spielmenüs", description: "Anprobe mit Creator-Kamera, Kategorien und Kauf für das Inventar.", source: "views/Clothing.tsx", css: "clothing.css", symbol: "STIL" },
  { id: "garage", title: "Garage", group: "Spielmenüs", description: "Eigene ESX-Fahrzeuge ein- und ausparken. Fahrer und Tor im Spiel testen.", source: "views/NativeMenu.tsx", css: "nativeui.css", symbol: "P" },
  { id: "garage-dev", title: "Garagenverwaltung", group: "Spielmenüs", description: "/rp_garage_dev: NPCs, Tor, Stellplätze und Fahrwege. Vorschau ohne Weltänderungen.", source: "views/NativeMenu.tsx", css: "nativeui.css", symbol: "DEV" },
  { id: "phone", title: "iFruit Handy", group: "Spielmenüs", description: "Pfeile, Enter und Zurück: Apps, Home und zuletzt geöffnete Apps. Im Spiel nur mit Handy-Item.", source: "views/Phone.tsx", css: "phone.css", symbol: "↑" },
  { id: "admin", title: "Administration", group: "Spielmenüs", description: "F10: Geld, Items, ESX-Noclip, Wegpunkt und Godmode. Vorschau ohne Spielaktionen.", source: "views/NativeMenu.tsx", css: "nativeui.css", symbol: "F10" },
  {
    id: "hud",
    title: "HUD",
    group: "Spielmenüs",
    description: "Bargeld, Sprachreichweite, Sprechstatus, Spielerzahl und deine ID.",
    source: "components/GameHud.tsx",
    css: "hud.css",
    symbol: "HUD",
  },
  {
    id: "interaction",
    title: "Interaktionshinweis",
    group: "Spielmenüs",
    description: "Taste und Aktion an Shops, Werkbänken und Bodenablagen.",
    source: "components/InteractionPrompt.tsx",
    css: "interaction.css",
    symbol: "E",
  },
  {
    id: "nativeui",
    title: "NativeUI",
    group: "Spielmenüs",
    description:
      "GTA-Interaktionsmenü: nur Pfeile, Enter und Zurück. Untermenüs, Listen und Checkboxen.",
    source: "views/NativeMenu.tsx",
    css: "nativeui.css",
    symbol: "NUI",
  },
  {
    id: "shop",
    title: "Shop",
    group: "Spielmenüs",
    description: "Sortiment, Mengen und ESX-Zahlung mit Bargeld oder Karte.",
    source: "views/Commerce.tsx",
    css: "commerce.css",
    symbol: "SHOP",
  },
  {
    id: "weaponshop",
    title: "Ammu-Nation",
    group: "Spielmenüs",
    description: "NativeMenu mit Waffen, Munition und Zubehör. 3D-Props und Kamera im Spiel testen.",
    source: "views/NativeMenu.tsx",
    css: "nativeui.css",
    symbol: "AMMU",
  },
  {
    id: "crafting",
    title: "Werkbank",
    group: "Spielmenüs",
    description: "Rezepte, Materialien und Herstellungsfortschritt.",
    source: "views/Commerce.tsx",
    css: "commerce.css",
    symbol: "CRAFT",
  },
  {
    id: "inventory",
    title: "Inventar",
    group: "Spielmenüs",
    description: "Slots, Rucksäcke, externe Behälter und Drag & Drop. Bodenprops im Spiel testen.",
    source: "views/Inventory.tsx",
    css: "inventory.css",
    symbol: "I",
  },
  {
    id: "organizations",
    title: "Organisationen",
    group: "Spielmenüs",
    description: "Berufe, Fraktionen, Mitglieder und Ränge verwalten.",
    source: "views/Organizations.tsx",
    css: "organizations.css",
    symbol: "ORG",
  },
  {
    id: "characters",
    title: "Charakterauswahl",
    group: "Einreise",
    description: "Bestehende Charaktere und freie Plätze.",
    source: "views/Characters.tsx",
    css: "styles.css",
    symbol: "01",
  },
  {
    id: "creator",
    title: "Charakter erstellen",
    group: "Einreise",
    description: "Identität, Aussehen, Haare und Kleidung.",
    source: "views/Characters.tsx",
    css: "creator.css",
    symbol: "02",
  },
  {
    id: "me",
    title: "Mein Charakter",
    group: "Spielmenüs",
    description: "Profil, Finanzen und Fitnessübersicht.",
    source: "views/Me.tsx",
    css: "menus.css",
    symbol: "M",
  },
  {
    id: "settings",
    title: "Einstellungen",
    group: "Spielmenüs",
    description: "Tastenbelegung und Konfliktdialoge.",
    source: "views/Settings.tsx",
    css: "menus.css",
    symbol: "F12",
  },
  {
    id: "loading",
    title: "Einreise lädt",
    group: "Zustände & Bausteine",
    description: "Ladezustand des Charakterablaufs.",
    source: "views/Characters.tsx",
    css: "styles.css",
    symbol: "↻",
  },
  {
    id: "error",
    title: "Einreise fehlgeschlagen",
    group: "Zustände & Bausteine",
    description: "Fehleranzeige und erneuter Versuch.",
    source: "views/Characters.tsx",
    css: "styles.css",
    symbol: "!",
  },
  {
    id: "welcome",
    title: "Allgemeiner Dialog",
    group: "Zustände & Bausteine",
    description: "Einfache Nachricht mit Schließen-Aktion.",
    source: "App.tsx",
    css: "styles.css",
    symbol: "↗",
  },
] as const;
export type ScreenId = (typeof screens)[number]["id"];
export const isScreenId = (value: string | null): value is ScreenId =>
  screens.some((screen) => screen.id === value);

export const viewports = {
  auto: { label: "An Fenster anpassen", width: 0, height: 0 },
  fullhd: { label: "1920 × 1080 · Full HD", width: 1920, height: 1080 },
  qhd: { label: "2560 × 1440 · QHD", width: 2560, height: 1440 },
  uhd: { label: "3840 × 2160 · 4K", width: 3840, height: 2160 },
  ultrawide: { label: "3440 × 1440 · Ultrawide", width: 3440, height: 1440 },
  laptop: { label: "1366 × 768 · Laptop", width: 1366, height: 768 },
  hd: { label: "1280 × 720 · HD", width: 1280, height: 720 },
  narrow: { label: "740 × 900 · Schmal", width: 740, height: 900 },
} as const;
export type ViewportId = keyof typeof viewports;
export const isViewportId = (value: string): value is ViewportId =>
  Object.hasOwn(viewports, value);
